njasm/marionette_client

client_test.go
transport.go

Timeouts on tcp connection

---

README.md

doc: Fix typo

---

.github/workflows/ci.yml
client.go
client_test.go

fix #28, and some ci.yml reordering

---

.github/workflows/ci.yml

Added MacOS platform to GHA CI.yml

Added MacOS platform to GHA CI

---

.github/workflows/ci.yml

Added parallel option to Coveralls CI action

Feature cc parallel

---

.github/bors.toml
.github/workflows/ci.yml
README.md
client.go
client_test.go

- Fixed some tests
- Removed Unused/Old Firefox Webdriver methods that are not present in latest FF versions
- Fixed ident code blocks in README.md

Changes to README and fixed some tests

---

client.go
client_test.go
navigation.go

removed deadcode/deprecated features in old versions that are not present anymore in recente FF versions.

more cleaning.

---

client.go
client_test.go
expected_test.go

refactor to remove dead/old code

---

client.go
client_test.go

added refactored timeouts feature and added new SetTimeouts() method

---

.github/workflows/ci.yml
Cookie.go
client.go
client_test.go
cookie.go

relates with #11 
Adds `WebDriver:AddCookie` command

added command WebDriver:AddCookie

---

client.go
client_test.go

added WebDriver:AddCookie, DeleteCookie and DeleteAllCookies commands

---

client.go
client_test.go
cookie.go

added WebDriver:GetTimeouts and WebDriver:GetCapabilities commands

---

client.go
client_test.go
expected_test.go

added WebDriver:NewWindow command plus more test coverage

---

.github/workflows/ci.yml

updated FF to version 84.0 for CI

---

client.go
client_test.go

added commands plus unit test
relates to #11 and #12

added WebDriver:MinimizeWindow and WebDriver:fullscreenWindow cmds

---

client.go
client_test.go

added WebDriver:ExecuteAsyncScript command

---

.github/workflows/ci.yml

added Firefox version 85.0 to CI

added FF 85.0 to CI tests

---

.github/workflows/ci.yml

added FF 86.0 and 87.0 to CI workflow

---

client.go
client_test.go
webelement.go

Add WebDriver GetActiveElement command.

---

client_test.go

add test for GetActiveElement command

---

.github/workflows/ci.yml
README.md
client.go
client_test.go
testdata/html/form.html
webelement.go

More commands and added new FF versions to CI

---

client.go

relates to ongoing work from #11

 Add WebDriver:CloseChromeWindow command

---

.github/workflows/ci.yml

Adds ff version 110.0.1 to CI pipeline

Adds ff version 110.0.1 to CI pipeline

---

.github/bors.toml
.github/workflows/ci.yml
README.md

- fix github badge link
- removed bors config file

chore: fix github badge link and removed bors config file
